python main_trans.py --Adapter_downsample=8 --accum_itr=4 \
	--batch_size=4 --decay=0.35 --decay_epoch=3 --early_stop=20 --epochs=50 --is_audio_adapter_p1=1 --is_audio_adapter_p2=1 \
	--is_audio_adapter_p3=0 --is_before_layernorm=1 --is_bn=1 --is_fusion_before=1 --is_gate=1  \
	--is_post_layernorm=1 --is_vit_ln=0 --lr=5e-04 --lr_mlp=5e-06 --mode=train \
    --num_conv_group=2 --num_tokens=32 --num_workers=16 --seed 42 \
	--backbone_type audioset \
    --root_path /projects/ec12/jinyueg/DG-SCT \
    --model=GEoPMA \
    --modality='av' \
    --lr=5e-05 --checkpoint='lr5e-5_W04_puc3ly4u' \
    --finetuned_ckpt_path='/projects/ec12/jinyueg/SoundActions/soundactions/logs/W04_all_Enjoyable_av_av/soundactions/puc3ly4u/checkpoints/epoch=41-step=3108.ckpt' \
    --finetuned_config_path='/projects/ec12/jinyueg/SoundActions/soundactions/logs/W04_all_Enjoyable_av_av/wandb/run-20240825_142920-j4rfmsge/files/config.yaml'